# Allow access to an ssh server bound to localhost
[[rules]]
# The username is optional, if not specified, any username is allowed
#username = "user"
# The ssh keys allowed to connect
ssh_keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
]
# Allowed destinations to connect to
permit = [
    "127.0.0.1:22",
    #"127.0.0.1:8080",
    #"127.0.0.1:*",
]

## Configuration for an ssh based proxy server (any destination is allowed)
#[[rules]]
#username = "proxy"
#ssh_keys = [
#    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
#]
#permit = ["*"]
