[sshd]
## Change the address and port the server binds to
#bind_addr = "[::]:2"

## Minimal configuration, permit any ssh key to connect to any destination
#[[rules]]
#ssh_keys = [
#    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
#]
#permit = ["*"]

## Rules are iterated over in order, if no rule matches, the connection is rejected.

## Allow access to an ssh server bound to localhost
#[[rules]]
## The username is optional, if not specified, any username is allowed
##username = "user"
## The ssh keys allowed to connect
#ssh_keys = [
#    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
#]
## Allowed destinations to connect to
#permit = [
#    "127.0.0.1:22",
#    #"127.0.0.1:*",
#]

## Allow access to http and https servers on the internet
#[[rules]]
#username = "proxy"
#ssh_keys = [
#    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
#]
#permit = [
#    "*:80",
#    "*:443",
#    #"example.com*:443",
#]

[honeypot]
## Change the SSH server banner to a custom string
## Note that invalid values may confuse or break clients
#spoof_server_id = "SSH-2.0-anything"
## Log unsolicited password authentication attempts (including the password) to stderr
#log_bruteforce_passwords = true
## Report unsolicited password authentication attempts to a remote server via http json post
## {"username":"root","password":"123456","src":"192.0.2.34:56789"}
#report_url_bruteforce_passwords = "https://example.com/report"
## In addition to unsolicited password authentication attempts,
## advertise that password authentication is supported/enabled
#bait_password_bruteforce = true
