[sshd]
## Change the address and port the server binds to
#bind_addr = "[::]:20"

[honeypot]
## Change the SSH server banner to a custom string
## Note that invalid values may confuse or break clients
#spoof_server_id = "SSH-2.0-anything"
## Log unsolicited password authentication attempts (including the password)
#log_bruteforce_passwords = true
## In addition to unsolicited password authentication attempts,
## advertise that password authentication is supported/enabled
#bait_password_bruteforce = true

# Allow access to an ssh server bound to localhost
[[rules]]
# The username is optional, if not specified, any username is allowed
#username = "user"
# The ssh keys allowed to connect
ssh_keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
]
# Allowed destinations to connect to
permit = [
    "127.0.0.1:22",
    #"127.0.0.1:8080",
    #"127.0.0.1:*",
]

## Configuration for an ssh based proxy server (any destination is allowed)
#[[rules]]
#username = "proxy"
#ssh_keys = [
#    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbVfiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
#]
#permit = ["*"]
